Adding SIG related information to Governance documentation
slsa-framework/governance pull request #15
Opened 2022-10-04 17:07 UTC by melba-lopez

original Issue: https://github.com/slsa-framework/slsa/issues/453

Added 1.6. Special Interest Group Members to Governance.md
Added Reporting Violations section with associated contacts to Code_of_Conduct.md
Added 3 files for SIG charters as they stand today.
Added Special Interest Groups section to Readme

Updated Readme.md

Related issues, PRs, docs:
https://github.com/slsa-framework/slsa/issues/384
https://github.com/slsa-framework/slsa-proposals/tree/main/0002
https://docs.google.com/document/d/1L1gEJMBIvE0IbpFi23FOUByDYlItSYPPJmKdhvJQYsg/edit#
@melba-lopez

2022-10-05 13:30 UTC, MarkLodato requested changes
This is great. Thank you, Melba! Overall LGTM. My comments are mostly nitpicks and suggestions, plus one important question on scope.

2022-10-05 13:30 UTC, MarkLodato commented on 10._Positioning_Charter.md
> +In addition to the Collaboration/Workstream process documented in [SLSA SIGs document](https://docs.google.com/document/d/1L1gEJMBIvE0IbpFi23FOUByDYlItSYPPJmKdhvJQYsg/edit#heading=h.1hce59kd4nn0), th
nit: can we make this charter stand-alone without linking to original proposal? It's not clear to me what, if anything, one is supposed to read in that doc related to this section.

Same below.

2022-10-06 02:09 UTC, melba-lopez commented on Readme.md
> +-   [Eric Tice]
fixed; will commit shortly

2022-10-06 02:13 UTC, melba-lopez commented on Readme.md
> +Specification
done; will commit shortly.

2022-10-06 02:17 UTC, melba-lopez commented on 11._Tooling_Charter.md
> +Please see [SLSA SIGs document](https://docs.google.com/document/d/1L1gEJMBIvE0IbpFi23FOUByDYlItSYPPJmKdhvJQYsg/edit#heading=h.1hce59kd4nn0) for more information.
done will commit shortly

2022-10-06 02:18 UTC, melba-lopez commented on 9._Specification_Charter.md
> +Please see [SLSA SIGs document](https://docs.google.com/document/d/1L1gEJMBIvE0IbpFi23FOUByDYlItSYPPJmKdhvJQYsg/edit#heading=h.1hce59kd4nn0) for more information.
done; will commit shortly

2022-10-06 02:20 UTC, melba-lopez commented on 8._Code_of_Conduct.md
> +-   Or any [Steering Committee Member](https://github.com/slsa-framework/governance#steering-committee)
done; will commit shortly

2022-10-06 02:40 UTC, melba-lopez commented on 10._Positioning_Charter.md
> +## Mission
Done; you will have to double-check I didn't miss anything once i've committed.

2022-10-06 02:40 UTC, melba-lopez commented on 10._Positioning_Charter.md
> +# Positioning SIG Charter
Done; will commit shortly

2022-10-06 03:47 UTC, closed without merging